version: '3.8'

services:
  postgres:
    image: postgres:16.2
    environment:
      POSTGRES_USER: ${PG_USER}
      POSTGRES_PASSWORD: ${PG_PWD}
      POSTGRES_DB: ${PG_DATABASE}
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "${PG_PORT}:5432"
    restart: unless-stopped

volumes:
  pgdata: